# Fine-tune TrOCR với Japanese BERT Decoder + LoRA trên Manga109-s (H100 Optimized)

**Kiến trúc mới (đã sửa)**:
- **Encoder**: ViT từ `microsoft/trocr-base-printed` (giữ nguyên pretrained weights)
- **Decoder**: `cl-tohoku/bert-base-japanese-char-v2` (pretrained Japanese BERT — không phải random weights)
- **LoRA**: Chỉ train ~2-3% tham số trên attention layers

**Tại sao thay đổi**:
Cách cũ (swap tokenizer vào TrOCR decoder) → decoder bắt đầu từ **random embedding** với English-pretrained weights → kết quả hỗn loạn.
Cách mới dùng JP BERT làm decoder thực sự → decoder có **prior knowledge về tiếng Nhật** ngay từ đầu.

## 1. Cài đặt dependencies

In [1]:
!pip install -q transformers datasets evaluate jiwer accelerate peft bitsandbytes
!pip install -q fugashi unidic-lite  # required for cl-tohoku tokenizer

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 39.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 89.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.4/47.4 MB 50.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 694.9/694.9 kB 42.8 MB/s eta 0:00:00
  Building wheel for unidic-lite (setup.py) ... done

## 2. Import thư viện + tối ưu H100

In [ ]:
import os
import random
import torch
import numpy as np
from PIL import Image
from datasets import Dataset
from transformers import (
    AutoFeatureExtractor,
    AutoTokenizer,
    VisionEncoderDecoderModel,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    default_data_collator,
    set_seed,
    )
import evaluate
from tqdm import tqdm
from peft import LoraConfig, get_peft_model

# ==================== REPRODUCIBILITY ====================
SEED = 42
set_seed(SEED)
random.seed(SEED)
np.random.seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ==================== H100 OPTIMIZATIONS ====================
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
print('H100 optimizations enabled (TF32 + bf16)')
print(f'Seed: {SEED}')

print('GPU available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('Device:', torch.cuda.get_device_name(0))

✅ H100 optimizations enabled (TF32 + bf16)
GPU available: True
Device: NVIDIA H100 80GB HBM3

## 3. Tải Manga109-s

In [ ]:
from huggingface_hub import snapshot_download

HF_TOKEN = ''
BASE_DIR = '/kaggle/working/manga109s_dataset'
os.makedirs(BASE_DIR, exist_ok=True)

print('📥 Đang tải Manga109-s...')
snapshot_download(
    repo_id='hal-utokyo/Manga109-s',
    repo_type='dataset',
    local_dir=BASE_DIR,
    token=HF_TOKEN,
)
print(f'✅ Tải xong. Files: {os.listdir(BASE_DIR)}')

📥 Đang tải Manga109-s...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

✅ Tải xong. Files: ['.cache', 'Manga109s_released_2023_12_07.zip', 'README.md', '.gitattributes']

## 4. Giải nén dataset

In [4]:
import zipfile

ZIP_PATH     = '/kaggle/working/manga109s_dataset/Manga109s_released_2023_12_07.zip'
EXTRACT_PATH = '/kaggle/working/manga109_extracted'
DATASET_ROOT = f'{EXTRACT_PATH}/Manga109s_released_2023_12_07'

if not os.path.exists(DATASET_ROOT) or not os.listdir(DATASET_ROOT):
    print('📦 Giải nén Manga109-s...')
    os.makedirs(EXTRACT_PATH, exist_ok=True)
    with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
        zf.extractall(EXTRACT_PATH)
    print('✅ Giải nén xong!')
else:
    print('✅ Đã giải nén trước đó, bỏ qua.')

print(f'Nội dung: {os.listdir(DATASET_ROOT)}')

📦 Giải nén Manga109-s...
✅ Giải nén xong!
Nội dung: ['books.txt', 'readme.txt', 'images', 'annotations.v2018.05.31', 'annotations_COO', 'annotations', 'annotations_Manga109Dialog', 'annotations.v2020.12.18']

## 5. Tạo REC dataset (crop text box)

In [5]:
import random
import xml.etree.ElementTree as ET
from typing import Optional

class Manga109RecDatasetCreator:
    def __init__(self, dataset_root: str):
        self.dataset_root    = dataset_root
        self.annotations_dir = os.path.join(dataset_root, 'annotations')
        self.images_dir      = os.path.join(dataset_root, 'images')

    def create_rec_dataset(
        self,
        output_dir: str = '/kaggle/working/train_data',
        min_width: int = 20,
        min_height: int = 20,
        max_samples: Optional[int] = 50000,
        train_ratio: float = 0.9,
        seed: int = 42,
    ):
        random.seed(seed)
        rec_dir = os.path.join(output_dir, 'rec')
        train_img_dir = os.path.join(rec_dir, 'train')
        val_img_dir   = os.path.join(rec_dir, 'val')
        os.makedirs(train_img_dir, exist_ok=True)
        os.makedirs(val_img_dir,   exist_ok=True)

        train_gt = os.path.join(rec_dir, 'rec_gt_train.txt')
        val_gt   = os.path.join(rec_dir, 'rec_gt_val.txt')

        xml_files = sorted(f for f in os.listdir(self.annotations_dir) if f.endswith('.xml'))
        print(f'🔍 Tìm thấy {len(xml_files)} truyện manga.')

        all_samples = []
        for xml_file in tqdm(xml_files, desc='Parsing manga'):
            book_title = os.path.splitext(xml_file)[0]
            xml_path   = os.path.join(self.annotations_dir, xml_file)
            try:
                root = ET.parse(xml_path).getroot()
            except:
                continue

            for page in root.findall('.//page'):
                page_idx = page.get('index')
                img_filename = f'{int(page_idx):03d}.jpg'
                img_path = os.path.join(self.images_dir, book_title, img_filename)
                if not os.path.exists(img_path):
                    continue
                try:
                    img = Image.open(img_path).convert('RGB')
                except:
                    continue

                for text_obj in page.findall('text'):
                    try:
                        xmin, ymin = int(text_obj.get('xmin')), int(text_obj.get('ymin'))
                        xmax, ymax = int(text_obj.get('xmax')), int(text_obj.get('ymax'))
                        label = (text_obj.text or '').strip().replace('\n', ' ').replace('\t', ' ')
                        if not label:
                            continue
                        if (xmax - xmin) < min_width or (ymax - ymin) < min_height:
                            continue
                        all_samples.append((img.crop((xmin, ymin, xmax, ymax)), label))
                    except:
                        continue

                if max_samples and len(all_samples) >= max_samples * 2:
                    break

        random.shuffle(all_samples)
        if max_samples:
            all_samples = all_samples[:max_samples]

        split_idx = int(len(all_samples) * train_ratio)
        train_samples = all_samples[:split_idx]
        val_samples   = all_samples[split_idx:]
        print(f'📊 Split: {len(train_samples):,} train | {len(val_samples):,} val')

        def save_split(samples, img_dir, gt_path, split_name, start_idx=1):
            with open(gt_path, 'w', encoding='utf-8') as f:
                for i, (crop, label) in enumerate(tqdm(samples, desc=f'Saving {split_name}'), start_idx):
                    img_name = f'word_{i:06d}.png'
                    crop.save(os.path.join(img_dir, img_name))
                    f.write(f'{split_name}/{img_name}\t{label}\n')

        save_split(train_samples, train_img_dir, train_gt, 'train')
        save_split(val_samples,   val_img_dir,   val_gt,   'val', len(train_samples)+1)
        print('✅ Dataset REC hoàn tất!')

creator = Manga109RecDatasetCreator(DATASET_ROOT)
creator.create_rec_dataset(
    output_dir   = '/kaggle/working/train_data',
    max_samples  = 50000,
    train_ratio  = 0.9,
    seed         = 42
)

🔍 Tìm thấy 87 truyện manga.

Parsing manga:   0%|          | 0/87 [00:00<?, ?it/s]
Parsing manga:   1%|          | 1/87 [00:00<01:07,  1.28it/s]
Parsing manga:   2%|▏         | 2/87 [00:01<01:05,  1.30it/s]
Parsing manga:   3%|▎         | 3/87 [00:02<01:06,  1.26it/s]
Parsing manga:   5%|▍         | 4/87 [00:02<01:00,  1.37it/s]
Parsing manga:   6%|▌         | 5/87 [00:03<01:01,  1.32it/s]
Parsing manga:   7%|▋         | 6/87 [00:04<01:03,  1.27it/s]
Parsing manga:   8%|▊         | 7/87 [00:05<01:05,  1.23it/s]
Parsing manga:   9%|▉         | 8/87 [00:06<01:12,  1.08it/s]
Parsing manga:  10%|█         | 9/87 [00:07<01:10,  1.11it/s]
Parsing manga:  11%|█▏        | 10/87 [00:08<01:12,  1.06it/s]
Parsing manga:  13%|█▎        | 11/87 [00:09<01:11,  1.07it/s]
Parsing manga:  14%|█▍        | 12/87 [00:10<01:10,  1.06it/s]
Parsing manga:  15%|█▍        | 13/87 [00:11<01:06,  1.11it/s]
Parsing manga:  16%|█▌        | 14/87 [00:12<01:04,  1.13it/s]
Parsing manga:  17%|█▋        | 15/87 [00:13<01:12,  1.01s/it]
Parsing manga:  18%|█▊        | 16/87 [00:14<01:12,  1.02s/it]
Parsing manga:  20%|█▉        | 17/87 [00:15<01:04,  1.09it/s]
Parsing manga:  21%|██        | 18/87 [00:15<01:01,  1.12it/s]
Parsing manga:  22%|██▏       | 19/87 [00:16<01:01,  1.10it/s]
Parsing manga:  23%|██▎       | 20/87 [00:17<01:00,  1.11it/s]
Parsing manga:  24%|██▍       | 21/87 [00:19<01:11,  1.09s/it]
Parsing manga:  25%|██▌       | 22/87 [00:20<01:06,  1.03s/it]
Parsing manga:  26%|██▋       | 23/87 [00:20<01:01,  1.05it/s]
Parsing manga:  28%|██▊       | 24/87 [00:21<00:56,  1.12it/s]
Parsing manga:  29%|██▊       | 25/87 [00:22<00:53,  1.15it/s]
Parsing manga:  30%|██▉       | 26/87 [00:23<00:55,  1.10it/s]
Parsing manga:  31%|███       | 27/87 [00:24<00:51,  1.16it/s]
Parsing manga:  32%|███▏      | 28/87 [00:25<00:49,  1.20it/s]
Parsing manga:  33%|███▎      | 29/87 [00:26<00:50,  1.15it/s]
Parsing manga:  34%|███▍      | 30/87 [00:26<00:44,  1.28it/s]
Parsing manga:  36%|███▌      | 31/87 [00:27<00:50,  1.12it/s]
Parsing manga:  37%|███▋      | 32/87 [00:28<00:47,  1.17it/s]
Parsing manga:  38%|███▊      | 33/87 [00:29<00:47,  1.13it/s]
Parsing manga:  39%|███▉      | 34/87 [00:30<00:47,  1.13it/s]
Parsing manga:  40%|████      | 35/87 [00:30<00:41,  1.25it/s]
Parsing manga:  41%|████▏     | 36/87 [00:31<00:41,  1.23it/s]
Parsing manga:  43%|████▎     | 37/87 [00:32<00:42,  1.18it/s]
Parsing manga:  44%|████▎     | 38/87 [00:33<00:42,  1.14it/s]
Parsing manga:  45%|████▍     | 39/87 [00:34<00:42,  1.13it/s]
Parsing manga:  46%|████▌     | 40/87 [00:35<00:39,  1.18it/s]
Parsing manga:  47%|████▋     | 41/87 [00:36<00:38,  1.20it/s]
Parsing manga:  48%|████▊     | 42/87 [00:36<00:35,  1.26it/s]
Parsing manga:  49%|████▉     | 43/87 [00:37<00:34,  1.26it/s]
Parsing manga:  51%|█████     | 44/87 [00:38<00:34,  1.24it/s]
Parsing manga:  52%|█████▏    | 45/87 [00:39<00:35,  1.20it/s]
Parsing manga:  53%|█████▎    | 46/87 [00:40<00:36,  1.12it/s]
Parsing manga:  54%|█████▍    | 47/87 [00:40<00:30,  1.29it/s]
Parsing manga:  55%|█████▌    | 48/87 [00:41<00:27,  1.43it/s]
Parsing manga:  56%|█████▋    | 49/87 [00:42<00:27,  1.38it/s]
Parsing manga:  57%|█████▋    | 50/87 [00:43<00:32,  1.14it/s]
Parsing manga:  59%|█████▊    | 51/87 [00:44<00:30,  1.19it/s]
Parsing manga:  60%|█████▉    | 52/87 [00:44<00:26,  1.32it/s]
Parsing manga:  61%|██████    | 53/87 [00:45<00:27,  1.23it/s]
Parsing manga:  62%|██████▏   | 54/87 [00:46<00:27,  1.21it/s]
Parsing manga:  63%|██████▎   | 55/87 [00:47<00:25,  1.27it/s]
Parsing manga:  64%|██████▍   | 56/87 [00:50<00:44,  1.45s/it]
Parsing manga:  66%|██████▌   | 57/87 [00:51<00:37,  1.26s/it]
Parsing manga:  67%|██████▋   | 58/87 [00:52<00:37,  1.28s/it]
Parsing manga:  68%|██████▊   | 59/87 [00:53<00:33,  1.21s/it]
Parsing manga:  69%|██████▉   | 60/87 [00:54<00:30,  1.13s/it]
Parsing manga:  70%|███████   | 61/87 [00:55<00:27,  1.04s/it]
Parsing manga:  71%|███████▏  | 62/87 [00:56<00:24,  1.03it/s]
Parsing manga:  72%|███████▏  | 63/87 [00:56<00:22,  1.09it/s]
Parsing manga:  74%|███████▎  | 64/87 [00:57<00:21,  1.07it/s]
Parsing manga:  75%|███████▍  | 65/87 [00:58<00:19,  1.14it/s]
Parsing manga:  76%|███████▌  | 66/87 [00:59<00:17,  1.19it/s]
Parsing manga:  77%|███████▋  | 67/87 [00:59<00:15,  1.25it/s]
Parsing manga:  78%|███████▊  | 68/87 [01:01<00:17,  1.09it/s]
Parsing manga:  79%|███████▉  | 69/87 [01:01<00:15,  1.14it/s]
Parsing manga:  80%|████████  | 70/87 [01:02<00:14,  1.19it/s]
Parsing manga:  82%|████████▏ | 71/87 [01:03<00:13,  1.19it/s]
Parsing manga:  83%|████████▎ | 72/87 [01:03<00:10,  1.44it/s]
Parsing manga:  84%|████████▍ | 73/87 [01:05<00:11,  1.20it/s]
Parsing manga:  85%|████████▌ | 74/87 [01:06<00:11,  1.13it/s]
Parsing manga:  86%|████████▌ | 75/87 [01:07<00:11,  1.04it/s]
Parsing manga:  87%|████████▋ | 76/87 [01:08<00:10,  1.09it/s]
Parsing manga:  89%|████████▊ | 77/87 [01:08<00:08,  1.17it/s]
Parsing manga:  90%|████████▉ | 78/87 [01:09<00:07,  1.21it/s]
Parsing manga:  91%|█████████ | 79/87 [01:10<00:07,  1.13it/s]
Parsing manga:  92%|█████████▏| 80/87 [01:11<00:05,  1.18it/s]
Parsing manga:  93%|█████████▎| 81/87 [01:12<00:04,  1.23it/s]
Parsing manga:  94%|█████████▍| 82/87 [01:13<00:04,  1.12it/s]
Parsing manga:  95%|█████████▌| 83/87 [01:13<00:03,  1.14it/s]
Parsing manga:  97%|█████████▋| 84/87 [01:14<00:02,  1.09it/s]
Parsing manga: 100%|██████████| 87/87 [01:15<00:00,  1.15it/s]

📊 Split: 45,000 train | 5,000 val

Saving train:   0%|          | 0/45000 [00:00<?, ?it/s]
Saving train:   0%|          | 1/45000 [00:00<1:52:51,  6.65it/s]
Saving train:   0%|          | 69/45000 [00:00<02:14, 334.54it/s]
Saving train:   0%|          | 119/45000 [00:00<01:51, 402.14it/s]
Saving train:   0%|          | 177/45000 [00:00<01:35, 467.09it/s]
Saving train:   1%|          | 242/45000 [00:00<01:24, 529.30it/s]
Saving train:   1%|          | 298/45000 [00:00<01:29, 501.64it/s]
Saving train:   1%|          | 350/45000 [00:00<01:41, 441.39it/s]
Saving train:   1%|          | 416/45000 [00:00<01:29, 495.66it/s]
Saving train:   1%|          | 471/45000 [00:01<01:27, 510.05it/s]
Saving train:   1%|          | 535/45000 [00:01<01:21, 543.83it/s]
Saving train:   1%|▏         | 591/45000 [00:01<01:22, 539.89it/s]
Saving train:   1%|▏         | 646/45000 [00:01<01:29, 493.37it/s]
Saving train:   2%|▏         | 700/45000 [00:01<01:27, 504.07it/s]
Saving train:   2%|▏         | 765/45000 [00:01<01:21, 542.73it/s]
Saving train:   2%|▏         | 821/45000 [00:01<01:52, 393.20it/s]
Saving train:   2%|▏         | 867/45000 [00:01<01:52, 393.69it/s]
Saving train:   2%|▏         | 920/45000 [00:02<01:43, 425.98it/s]
Saving train:   2%|▏         | 979/45000 [00:02<01:34, 466.66it/s]
Saving train:   2%|▏         | 1035/45000 [00:02<01:30, 487.72it/s]
Saving train:   2%|▏         | 1087/45000 [00:02<01:32, 476.18it/s]
Saving train:   3%|▎         | 1155/45000 [00:02<01:22, 529.77it/s]
Saving train:   3%|▎         | 1219/45000 [00:02<01:19, 547.66it/s]
Saving train:   3%|▎         | 1276/45000 [00:02<01:24, 514.41it/s]
Saving train:   3%|▎         | 1333/45000 [00:02<01:23, 522.38it/s]
Saving train:   3%|▎         | 1389/45000 [00:02<01:21, 532.10it/s]
Saving train:   3%|▎         | 1446/45000 [00:02<01:20, 540.95it/s]
Saving train:   3%|▎         | 1511/45000 [00:03<01:16, 572.21it/s]
Saving train:   3%|▎         | 1569/45000 [00:03<01:16, 564.35it/s]
Saving train:   4%|▎         | 1626/45000 [00:03<01:17, 558.95it/s]
Saving train:   4%|▎         | 1683/45000 [00:03<01:17, 561.32it/s]
Saving train:   4%|▍         | 1740/45000 [00:03<01:19, 541.13it/s]
Saving train:   4%|▍         | 1795/45000 [00:03<01:24, 512.51it/s]
Saving train:   4%|▍         | 1856/45000 [00:03<01:20, 538.91it/s]
Saving train:   4%|▍         | 1911/45000 [00:04<02:26, 293.75it/s]
Saving train:   4%|▍         | 1970/45000 [00:04<02:03, 347.02it/s]
Saving train:   5%|▍         | 2030/45000 [00:04<01:47, 398.22it/s]
Saving train:   5%|▍         | 2088/45000 [00:04<01:38, 437.65it/s]
Saving train:   5%|▍         | 2153/45000 [00:04<01:28, 485.67it/s]
Saving train:   5%|▍         | 2216/45000 [00:04<01:21, 521.84it/s]
Saving train:   5%|▌         | 2274/45000 [00:04<01:21, 523.86it/s]
Saving train:   5%|▌         | 2338/45000 [00:04<01:17, 552.61it/s]
Saving train:   5%|▌         | 2397/45000 [00:04<01:18, 541.71it/s]
Saving train:   5%|▌         | 2463/45000 [00:05<01:14, 572.98it/s]
Saving train:   6%|▌         | 2523/45000 [00:05<01:14, 569.90it/s]
Saving train:   6%|▌         | 2582/45000 [00:05<01:15, 559.51it/s]
Saving train:   6%|▌         | 2648/45000 [00:05<01:12, 587.09it/s]
Saving train:   6%|▌         | 2708/45000 [00:05<01:11, 588.03it/s]
Saving train:   6%|▌         | 2768/45000 [00:05<01:15, 562.46it/s]
Saving train:   6%|▋         | 2836/45000 [00:05<01:10, 594.19it/s]
Saving train:   6%|▋         | 2896/45000 [00:05<01:11, 588.33it/s]
Saving train:   7%|▋         | 2956/45000 [00:05<01:14, 564.36it/s]
Saving train:   7%|▋         | 3022/45000 [00:06<01:10, 591.24it/s]
Saving train:   7%|▋         | 3082/45000 [00:06<01:13, 568.05it/s]
Saving train:   7%|▋         | 3142/45000 [00:06<01:15, 552.78it/s]
Saving train:   7%|▋         | 3203/45000 [00:06<01:14, 561.90it/s]
Saving train:   7%|▋         | 3269/45000 [00:06<01:10, 589.52it/s]
Saving train:   7%|▋         | 3333/45000 [00:06<01:09, 602.44it/s]
Saving train:   8%|▊         | 3402/45000 [00:06<01:06, 623.19it/s]
Saving train:   8%|▊         | 3465/45000 [00:06<01:08, 608.07it/s]
Saving train:   8%|▊         | 3527/45000 [00:06<01:10, 587.59it/s]
Saving train:   8%|▊         | 3587/45000 [00:07<01:11, 575.49it/s]
Saving train:   8%|▊         | 3650/45000 [00:07<01:09, 590.90it/s]
Saving train:   8%|▊         | 3714/45000 [00:07<01:08, 604.35it/s]
Saving train:   8%|▊         | 3775/45000 [00:07<01:09, 592.29it/s]
Saving train:   9%|▊         | 3839/45000 [00:07<01:07, 605.76it/s]
Saving train:   9%|▊         | 3900/45000 [00:07<01:13, 558.40it/s]
Saving train:   9%|▉         | 3958/45000 [00:07<01:12, 563.68it/s]
Saving train:   9%|▉         | 4015/45000 [00:07<01:12, 563.47it/s]
Saving train:   9%|▉         | 4087/45000 [00:07<01:07, 605.70it/s]
Saving train:   9%|▉         | 4148/45000 [00:07<01:09, 591.81it/s]
Saving train:   9%|▉         | 4208/45000 [00:08<01:09, 591.07it/s]
Saving train:   9%|▉         | 4268/45000 [00:08<01:11, 573.05it/s]
Saving train:  10%|▉         | 4326/45000 [00:08<01:13, 550.54it/s]
Saving train:  10%|▉         | 4389/45000 [00:08<01:11, 568.49it/s]
Saving train:  10%|▉         | 4447/45000 [00:08<01:11, 569.69it/s]
Saving train:  10%|█         | 4505/45000 [00:08<01:12, 561.29it/s]
Saving train:  10%|█         | 4562/45000 [00:08<01:16, 530.44it/s]
Saving train:  10%|█         | 4616/45000 [00:08<01:18, 515.08it/s]
Saving train:  10%|█         | 4673/45000 [00:08<01:16, 528.06it/s]
Saving train:  11%|█         | 4741/45000 [00:09<01:10, 570.19it/s]
Saving train:  11%|█         | 4799/45000 [00:09<01:12, 557.22it/s]
Saving train:  11%|█         | 4856/45000 [00:09<01:21, 494.69it/s]
Saving train:  11%|█         | 4908/45000 [00:09<01:19, 501.33it/s]
Saving train:  11%|█         | 4960/45000 [00:09<01:19, 502.82it/s]
Saving train:  11%|█         | 5013/45000 [00:09<01:18, 508.00it/s]
Saving train:  11%|█▏        | 5069/45000 [00:09<01:16, 521.85it/s]
Saving train:  11%|█▏        | 5122/45000 [00:09<01:23, 476.56it/s]
Saving train:  11%|█▏        | 5173/45000 [00:09<01:22, 484.77it/s]
Saving train:  12%|█▏        | 5243/45000 [00:10<01:13, 539.45it/s]
Saving train:  12%|█▏        | 5300/45000 [00:10<01:12, 547.39it/s]
Saving train:  12%|█▏        | 5364/45000 [00:10<01:09, 573.07it/s]
Saving train:  12%|█▏        | 5422/45000 [00:10<01:12, 545.67it/s]
Saving train:  12%|█▏        | 5481/45000 [00:10<01:11, 556.38it/s]
Saving train:  12%|█▏        | 5538/45000 [00:10<01:13, 537.45it/s]
Saving train:  12%|█▏        | 5593/45000 [00:10<01:14, 526.03it/s]
Saving train:  13%|█▎        | 5646/45000 [00:10<01:16, 514.53it/s]
Saving train:  13%|█▎        | 5701/45000 [00:10<01:15, 518.65it/s]
Saving train:  13%|█▎        | 5761/45000 [00:10<01:12, 540.19it/s]
Saving train:  13%|█▎        | 5816/45000 [00:11<01:16, 514.06it/s]
Saving train:  13%|█▎        | 5875/45000 [00:11<01:13, 530.38it/s]
Saving train:  13%|█▎        | 5947/45000 [00:11<01:07, 582.53it/s]
Saving train:  13%|█▎        | 6013/45000 [00:11<01:04, 603.63it/s]
Saving train:  14%|█▎        | 6077/45000 [00:11<01:03, 612.16it/s]
Saving train:  14%|█▎        | 6139/45000 [00:11<01:07, 572.66it/s]
Saving train:  14%|█▍        | 6200/45000 [00:11<01:07, 578.06it/s]
Saving train:  14%|█▍        | 6259/45000 [00:11<01:10, 547.41it/s]
Saving train:  14%|█▍        | 6327/45000 [00:11<01:06, 580.18it/s]
Saving train:  14%|█▍        | 6392/45000 [00:12<01:04, 597.73it/s]
Saving train:  14%|█▍        | 6453/45000 [00:12<01:04, 598.95it/s]
Saving train:  14%|█▍        | 6514/45000 [00:12<01:05, 589.38it/s]
Saving train:  15%|█▍        | 6574/45000 [00:12<01:05, 583.14it/s]
Saving train:  15%|█▍        | 6633/45000 [00:12<01:05, 583.47it/s]
Saving train:  15%|█▍        | 6692/45000 [00:12<01:07, 570.93it/s]
Saving train:  15%|█▌        | 6750/45000 [00:12<01:10, 543.49it/s]
Saving train:  15%|█▌        | 6805/45000 [00:12<01:16, 496.20it/s]
Saving train:  15%|█▌        | 6864/45000 [00:12<01:13, 520.31it/s]
Saving train:  15%|█▌        | 6919/45000 [00:13<01:13, 520.35it/s]
Saving train:  15%|█▌        | 6972/45000 [00:13<01:13, 519.22it/s]
Saving train:  16%|█▌        | 7033/45000 [00:13<01:09, 544.72it/s]
Saving train:  16%|█▌        | 7088/45000 [00:13<01:11, 526.82it/s]
Saving train:  16%|█▌        | 7142/45000 [00:13<01:14, 510.96it/s]
Saving train:  16%|█▌        | 7207/45000 [00:13<01:08, 548.26it/s]
Saving train:  16%|█▌        | 7265/45000 [00:13<01:08, 550.70it/s]
Saving train:  16%|█▋        | 7321/45000 [00:13<01:10, 538.01it/s]
Saving train:  16%|█▋        | 7376/45000 [00:13<01:10, 532.21it/s]
Saving train:  17%|█▋        | 7430/45000 [00:14<01:12, 515.29it/s]
Saving train:  17%|█▋        | 7482/45000 [00:14<01:12, 515.31it/s]
Saving train:  17%|█▋        | 7540/45000 [00:14<01:10, 533.84it/s]
Saving train:  17%|█▋        | 7607/45000 [00:14<01:05, 572.88it/s]
Saving train:  17%|█▋        | 7672/45000 [00:14<01:02, 594.62it/s]
Saving train:  17%|█▋        | 7732/45000 [00:14<01:02, 592.23it/s]
Saving train:  17%|█▋        | 7795/45000 [00:14<01:01, 602.91it/s]
Saving train:  17%|█▋        | 7856/45000 [00:14<01:03, 588.49it/s]
Saving train:  18%|█▊        | 7916/45000 [00:14<01:06, 559.13it/s]
Saving train:  18%|█▊        | 7973/45000 [00:14<01:12, 513.74it/s]
Saving train:  18%|█▊        | 8028/45000 [00:15<01:10, 521.51it/s]
Saving train:  18%|█▊        | 8086/45000 [00:15<01:09, 532.43it/s]
Saving train:  18%|█▊        | 8140/45000 [00:15<01:12, 507.56it/s]
Saving train:  18%|█▊        | 8202/45000 [00:15<01:08, 537.86it/s]
Saving train:  18%|█▊        | 8262/45000 [00:15<01:06, 548.87it/s]
Saving train:  18%|█▊        | 8321/45000 [00:15<01:05, 559.05it/s]
Saving train:  19%|█▊        | 8378/45000 [00:15<01:10, 521.04it/s]
Saving train:  19%|█▉        | 8439/45000 [00:15<01:07, 545.41it/s]
Saving train:  19%|█▉        | 8495/45000 [00:15<01:12, 505.77it/s]
Saving train:  19%|█▉        | 8558/45000 [00:16<01:07, 538.85it/s]
Saving train:  19%|█▉        | 8615/45000 [00:16<01:08, 534.11it/s]
Saving train:  19%|█▉        | 8670/45000 [00:16<01:11, 511.53it/s]
Saving train:  19%|█▉        | 8724/45000 [00:16<01:09, 518.79it/s]
Saving train:  20%|█▉        | 8777/45000 [00:16<01:09, 517.75it/s]
Saving train:  20%|█▉        | 8838/45000 [00:16<01:06, 543.93it/s]
Saving train:  20%|█▉        | 8899/45000 [00:16<01:04, 555.72it/s]
Saving train:  20%|█▉        | 8958/45000 [00:16<01:03, 564.34it/s]
Saving train:  20%|██        | 9016/45000 [00:16<01:04, 561.94it/s]
Saving train:  20%|██        | 9073/45000 [00:17<01:06, 540.41it/s]
Saving train:  20%|██        | 9134/45000 [00:17<01:04, 560.08it/s]
Saving train:  20%|██        | 9191/45000 [00:17<01:12, 491.33it/s]
Saving train:  21%|██        | 9242/45000 [00:17<01:12, 494.18it/s]
Saving train:  21%|██        | 9298/45000 [00:17<01:09, 511.80it/s]
Saving train:  21%|██        | 9351/45000 [00:17<01:09, 516.42it/s]
Saving train:  21%|██        | 9404/45000 [00:17<01:09, 512.51it/s]
Saving train:  21%|██        | 9460/45000 [00:17<01:07, 524.44it/s]
Saving train:  21%|██        | 9513/45000 [00:17<01:07, 525.74it/s]
Saving train:  21%|██▏       | 9566/45000 [00:18<01:15, 469.94it/s]
Saving train:  21%|██▏       | 9618/45000 [00:18<01:13, 481.78it/s]
Saving train:  21%|██▏       | 9668/45000 [00:18<01:15, 465.74it/s]
Saving train:  22%|██▏       | 9722/45000 [00:18<01:13, 482.81it/s]
Saving train:  22%|██▏       | 9771/45000 [00:18<01:12, 483.75it/s]
Saving train:  22%|██▏       | 9830/45000 [00:18<01:08, 512.95it/s]
Saving train:  22%|██▏       | 9897/45000 [00:18<01:02, 557.22it/s]
Saving train:  22%|██▏       | 9955/45000 [00:18<01:02, 562.80it/s]
Saving train:  22%|██▏       | 10012/45000 [00:18<01:04, 542.82it/s]
Saving train:  22%|██▏       | 10072/45000 [00:18<01:02, 554.71it/s]
Saving train:  23%|██▎       | 10142/45000 [00:19<00:58, 596.52it/s]
Saving train:  23%|██▎       | 10202/45000 [00:19<01:04, 541.43it/s]
Saving train:  23%|██▎       | 10258/45000 [00:19<01:07, 514.21it/s]
Saving train:  23%|██▎       | 10312/45000 [00:19<01:06, 520.06it/s]
Saving train:  23%|██▎       | 10368/45000 [00:19<01:05, 529.51it/s]
Saving train:  23%|██▎       | 10439/45000 [00:19<00:59, 578.16it/s]
Saving train:  23%|██▎       | 10498/45000 [00:19<01:02, 551.74it/s]
Saving train:  23%|██▎       | 10554/45000 [00:19<01:02, 551.40it/s]
Saving train:  24%|██▎       | 10617/45000 [00:19<01:00, 572.61it/s]
Saving train:  24%|██▎       | 10675/45000 [00:20<01:01, 556.15it/s]
Saving train:  24%|██▍       | 10732/45000 [00:20<01:01, 556.50it/s]
Saving train:  24%|██▍       | 10788/45000 [00:20<01:03, 541.92it/s]
Saving train:  24%|██▍       | 10843/45000 [00:20<01:12, 473.42it/s]
Saving train:  24%|██▍       | 10902/45000 [00:20<01:07, 502.61it/s]
Saving train:  24%|██▍       | 10962/45000 [00:20<01:04, 527.09it/s]
Saving train:  24%|██▍       | 11021/45000 [00:20<01:02, 543.67it/s]
Saving train:  25%|██▍       | 11077/45000 [00:20<01:03, 534.93it/s]
Saving train:  25%|██▍       | 11148/45000 [00:20<00:58, 582.28it/s]
Saving train:  25%|██▍       | 11213/45000 [00:21<00:56, 597.08it/s]
Saving train:  25%|██▌       | 11274/45000 [00:21<00:57, 582.49it/s]
Saving train:  25%|██▌       | 11341/45000 [00:21<00:55, 605.38it/s]
Saving train:  25%|██▌       | 11402/45000 [00:21<00:57, 581.77it/s]
Saving train:  25%|██▌       | 11461/45000 [00:21<01:03, 526.40it/s]
Saving train:  26%|██▌       | 11515/45000 [00:21<01:08, 486.91it/s]
Saving train:  26%|██▌       | 11582/45000 [00:21<01:02, 533.11it/s]
Saving train:  26%|██▌       | 11637/45000 [00:21<01:03, 527.87it/s]
Saving train:  26%|██▌       | 11691/45000 [00:21<01:04, 513.67it/s]
Saving train:  26%|██▌       | 11744/45000 [00:22<01:04, 514.55it/s]
Saving train:  26%|██▌       | 11806/45000 [00:22<01:02, 534.19it/s]
Saving train:  26%|██▋       | 11863/45000 [00:22<01:00, 544.06it/s]
Saving train:  26%|██▋       | 11920/45000 [00:22<01:00, 551.33it/s]
Saving train:  27%|██▋       | 11976/45000 [00:22<01:03, 521.04it/s]
Saving train:  27%|██▋       | 12041/45000 [00:22<00:59, 553.59it/s]
Saving train:  27%|██▋       | 12100/45000 [00:22<00:59, 551.32it/s]
Saving train:  27%|██▋       | 12156/45000 [00:22<01:02, 527.19it/s]
Saving train:  27%|██▋       | 12213/45000 [00:22<01:02, 520.79it/s]
Saving train:  27%|██▋       | 12266/45000 [00:23<01:03, 511.82it/s]
Saving train:  27%|██▋       | 12325/45000 [00:23<01:01, 528.54it/s]
Saving train:  28%|██▊       | 12391/45000 [00:23<00:57, 565.16it/s]
Saving train:  28%|██▊       | 12448/45000 [00:23<00:58, 559.15it/s]
Saving train:  28%|██▊       | 12508/45000 [00:23<00:56, 570.69it/s]
Saving train:  28%|██▊       | 12566/45000 [00:23<00:57, 565.25it/s]
Saving train:  28%|██▊       | 12627/45000 [00:23<00:56, 576.92it/s]
Saving train:  28%|██▊       | 12687/45000 [00:23<00:55, 577.29it/s]
Saving train:  28%|██▊       | 12749/45000 [00:23<00:54, 589.01it/s]
Saving train:  28%|██▊       | 12808/45000 [00:23<00:57, 561.06it/s]
Saving train:  29%|██▊       | 12865/45000 [00:24<00:59, 535.59it/s]
Saving train:  29%|██▊       | 12919/45000 [00:24<01:01, 522.30it/s]
Saving train:  29%|██▉       | 12972/45000 [00:24<01:01, 524.44it/s]
Saving train:  29%|██▉       | 13040/45000 [00:24<00:56, 567.32it/s]
Saving train:  29%|██▉       | 13098/45000 [00:24<00:56, 562.08it/s]
Saving train:  29%|██▉       | 13155/45000 [00:24<00:56, 560.11it/s]
Saving train:  29%|██▉       | 13218/45000 [00:24<00:54, 578.62it/s]
Saving train:  30%|██▉       | 13277/45000 [00:24<00:58, 544.22it/s]
Saving train:  30%|██▉       | 13336/45000 [00:24<00:57, 552.23it/s]
Saving train:  30%|██▉       | 13400/45000 [00:25<00:54, 575.28it/s]
Saving train:  30%|██▉       | 13458/45000 [00:25<00:55, 564.13it/s]
Saving train:  30%|███       | 13515/45000 [00:25<00:58, 537.35it/s]
Saving train:  30%|███       | 13570/45000 [00:25<00:59, 530.79it/s]
Saving train:  30%|███       | 13624/45000 [00:25<01:00, 522.60it/s]
Saving train:  30%|███       | 13680/45000 [00:25<00:58, 530.95it/s]
Saving train:  31%|███       | 13748/45000 [00:25<00:54, 570.08it/s]
Saving train:  31%|███       | 13806/45000 [00:25<00:54, 568.20it/s]
Saving train:  31%|███       | 13864/45000 [00:25<00:54, 568.36it/s]
Saving train:  31%|███       | 13935/45000 [00:25<00:51, 602.67it/s]
Saving train:  31%|███       | 13996/45000 [00:26<00:53, 576.79it/s]
Saving train:  31%|███       | 14056/45000 [00:26<00:53, 582.67it/s]
Saving train:  31%|███▏      | 14122/45000 [00:26<00:51, 604.86it/s]
Saving train:  32%|███▏      | 14183/45000 [00:26<00:54, 569.43it/s]
Saving train:  32%|███▏      | 14241/45000 [00:26<00:57, 538.67it/s]
Saving train:  32%|███▏      | 14300/45000 [00:26<00:55, 549.90it/s]
Saving train:  32%|███▏      | 14356/45000 [00:26<00:55, 552.02it/s]
Saving train:  32%|███▏      | 14412/45000 [00:26<00:56, 539.89it/s]
Saving train:  32%|███▏      | 14469/45000 [00:26<00:56, 542.81it/s]
Saving train:  32%|███▏      | 14527/45000 [00:27<00:55, 552.49it/s]
Saving train:  32%|███▏      | 14583/45000 [00:27<00:56, 542.70it/s]
Saving train:  33%|███▎      | 14638/45000 [00:27<00:57, 529.76it/s]
Saving train:  33%|███▎      | 14696/45000 [00:27<00:55, 543.58it/s]
Saving train:  33%|███▎      | 14758/45000 [00:27<00:53, 564.50it/s]
Saving train:  33%|███▎      | 14815/45000 [00:27<00:55, 544.25it/s]
Saving train:  33%|███▎      | 14873/45000 [00:27<00:54, 553.63it/s]
Saving train:  33%|███▎      | 14929/45000 [00:27<00:56, 535.62it/s]
Saving train:  33%|███▎      | 14994/45000 [00:27<00:53, 562.96it/s]
Saving train:  33%|███▎      | 15051/45000 [00:28<00:56, 530.21it/s]
Saving train:  34%|███▎      | 15113/45000 [00:28<00:54, 551.24it/s]
Saving train:  34%|███▎      | 15177/45000 [00:28<00:51, 575.21it/s]
Saving train:  34%|███▍      | 15242/45000 [00:28<00:50, 592.97it/s]
Saving train:  34%|███▍      | 15302/45000 [00:28<00:53, 556.35it/s]
Saving train:  34%|███▍      | 15359/45000 [00:28<00:53, 554.53it/s]
Saving train:  34%|███▍      | 15415/45000 [00:28<00:55, 529.87it/s]
Saving train:  34%|███▍      | 15474/45000 [00:28<00:54, 546.21it/s]
Saving train:  35%|███▍      | 15530/45000 [00:28<00:54, 536.36it/s]
Saving train:  35%|███▍      | 15594/45000 [00:29<00:52, 564.77it/s]
Saving train:  35%|███▍      | 15654/45000 [00:29<00:51, 574.31it/s]
Saving train:  35%|███▍      | 15712/45000 [00:29<00:51, 572.55it/s]
Saving train:  35%|███▌      | 15783/45000 [00:29<00:47, 611.37it/s]
Saving train:  35%|███▌      | 15847/45000 [00:29<00:47, 612.93it/s]
Saving train:  35%|███▌      | 15909/45000 [00:29<00:47, 607.66it/s]
Saving train:  35%|███▌      | 15970/45000 [00:29<00:48, 596.24it/s]
Saving train:  36%|███▌      | 16031/45000 [00:29<00:48, 595.66it/s]
Saving train:  36%|███▌      | 16091/45000 [00:29<00:49, 586.04it/s]
Saving train:  36%|███▌      | 16161/45000 [00:29<00:48, 600.79it/s]
Saving train:  36%|███▌      | 16222/45000 [00:30<00:49, 578.63it/s]
Saving train:  36%|███▌      | 16282/45000 [00:30<00:49, 574.51it/s]
Saving train:  36%|███▋      | 16340/45000 [00:30<00:53, 532.06it/s]
Saving train:  36%|███▋      | 16403/45000 [00:30<00:51, 558.70it/s]
Saving train:  37%|███▋      | 16460/45000 [00:30<00:51, 551.10it/s]
Saving train:  37%|███▋      | 16518/45000 [00:30<00:50, 558.89it/s]
Saving train:  37%|███▋      | 16575/45000 [00:30<00:54, 521.47it/s]
Saving train:  37%|███▋      | 16628/45000 [00:30<00:56, 506.25it/s]
Saving train:  37%|███▋      | 16680/45000 [00:30<00:58, 485.12it/s]
Saving train:  37%|███▋      | 16745/45000 [00:31<00:53, 530.01it/s]
Saving train:  37%|███▋      | 16799/45000 [00:31<00:53, 527.00it/s]
Saving train:  37%|███▋      | 16853/45000 [00:31<00:54, 518.39it/s]
Saving train:  38%|███▊      | 16910/45000 [00:31<00:52, 532.27it/s]
Saving train:  38%|███▊      | 16968/45000 [00:31<00:51, 544.57it/s]
Saving train:  38%|███▊      | 17028/45000 [00:31<00:50, 557.68it/s]
Saving train:  38%|███▊      | 17092/45000 [00:31<00:47, 581.52it/s]
Saving train:  38%|███▊      | 17153/45000 [00:31<00:47, 581.66it/s]

✅ Dataset REC hoàn tất!

In [ ]:
import os
import re
import unicodedata
from datasets import Dataset

REC_ROOT = '/kaggle/working/train_data/rec'

TRAIN_IMG_DIR = os.path.join(REC_ROOT, 'train')
VAL_IMG_DIR   = os.path.join(REC_ROOT, 'val')
TRAIN_GT      = os.path.join(REC_ROOT, 'rec_gt_train.txt')
VAL_GT        = os.path.join(REC_ROOT, 'rec_gt_val.txt')

MIN_CHARS = 2
MAX_CHARS = 80

def normalize_jp_text(text: str) -> str:
    text = unicodedata.normalize('NFKC', text)
    text = text.replace('\u3000', ' ')
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def load_gt_file(gt_path, img_base_dir):
    samples = []
    dropped_empty = 0
    dropped_short = 0
    dropped_long = 0
    dropped_missing_img = 0
    dropped_parse_error = 0

    with open(gt_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rel_path, text = line.split('\t', 1)
                img_path = os.path.join(img_base_dir, os.path.basename(rel_path))
                if not os.path.exists(img_path):
                    dropped_missing_img += 1
                    continue

                text = normalize_jp_text(text)
                if not text:
                    dropped_empty += 1
                    continue
                if len(text) < MIN_CHARS:
                    dropped_short += 1
                    continue
                if len(text) > MAX_CHARS:
                    dropped_long += 1
                    continue

                samples.append({'img_path': img_path, 'text': text})
            except Exception:
                dropped_parse_error += 1

    stats = {
        'kept': len(samples),
        'dropped_empty': dropped_empty,
        'dropped_short': dropped_short,
        'dropped_long': dropped_long,
        'dropped_missing_img': dropped_missing_img,
        'dropped_parse_error': dropped_parse_error,
    }
    return samples, stats

train_samples, train_stats = load_gt_file(TRAIN_GT, TRAIN_IMG_DIR)
val_samples, val_stats     = load_gt_file(VAL_GT,   VAL_IMG_DIR)

train_dataset = Dataset.from_list(train_samples)
val_dataset   = Dataset.from_list(val_samples)

print(f"Train: {len(train_dataset):,} | Val: {len(val_dataset):,}")
print('Train stats:', train_stats)
print('Val stats:  ', val_stats)

Train: 45,000 | Val: 5,000

## 6. Load Model: TrOCR Encoder + Japanese BERT Decoder

> **Đây là thay đổi cốt lõi so với notebook cũ.**

Thay vì swap tokenizer vào decoder của TrOCR (khiến decoder bắt đầu từ random embedding),
ta dùng `from_encoder_decoder_pretrained()` để ghép:
- **Encoder**: ViT của TrOCR — đã pretrain nhận dạng ảnh văn bản
- **Decoder**: `cl-tohoku/bert-base-japanese-char-v2` — pretrained Japanese BERT thực sự

Cross-attention layers (kết nối encoder-decoder) sẽ được khởi tạo ngẫu nhiên và cần được train.
LoRA sẽ cover cả hai phần này.

In [7]:
from transformers import (
    AutoImageProcessor,
    AutoTokenizer,
    BertJapaneseTokenizer,
    VisionEncoderDecoderModel,
    ViTModel,                        # load encoder trực tiếp
    BertLMHeadModel,                 # load decoder trực tiếp
    VisionEncoderDecoderConfig,
)
from peft import get_peft_model, LoraConfig

ENCODER_MODEL = 'microsoft/trocr-base-printed'
DECODER_MODEL = 'cl-tohoku/bert-base-japanese-char-v2'

# ================== IMAGE PROCESSOR + TOKENIZER ==================
print('🖼️  Loading image processor...')
feature_extractor = AutoImageProcessor.from_pretrained(ENCODER_MODEL)

print('🔤 Loading Japanese tokenizer...')
jp_tokenizer = BertJapaneseTokenizer.from_pretrained(DECODER_MODEL)
print(f'   Vocab size: {len(jp_tokenizer)}')

# Verify tokenizer
sample = 'その手紙は届いた'
print(f"   Sample: '{sample}' → {jp_tokenizer.tokenize(sample)}")

# ================== LOAD ENCODER & DECODER RIÊNG ==================
# Lấy encoder ViT từ bên trong TrOCR
print('🏗️  Loading TrOCR encoder (ViT)...')
trocr_full = VisionEncoderDecoderModel.from_pretrained(ENCODER_MODEL)
encoder = trocr_full.encoder   # ViTModel đã pretrain
del trocr_full                 # giải phóng memory

# Load JP BERT làm decoder — bật is_decoder + cross_attention
print('🏗️  Loading JP BERT decoder...')
decoder = BertLMHeadModel.from_pretrained(
    DECODER_MODEL,
    is_decoder=True,
    add_cross_attention=True,
)

# ================== GHÉP LẠI ==================
print('🔗 Assembling VisionEncoderDecoderModel...')
model = VisionEncoderDecoderModel(encoder=encoder, decoder=decoder)


# ================== CẤU HÌNH DECODER ==================
model.config.decoder_start_token_id = jp_tokenizer.cls_token_id
model.config.pad_token_id           = jp_tokenizer.pad_token_id
model.config.eos_token_id           = jp_tokenizer.sep_token_id
model.config.decoder.vocab_size     = len(jp_tokenizer)
model.config.use_cache              = False

# FIX: set thêm vào generation_config — model.config và generation_config là 2 object riêng
model.generation_config.decoder_start_token_id = jp_tokenizer.cls_token_id
model.generation_config.pad_token_id           = jp_tokenizer.pad_token_id
model.generation_config.eos_token_id           = jp_tokenizer.sep_token_id
model.generation_config.bos_token_id           = jp_tokenizer.cls_token_id  # fallback
model.generation_config.max_new_tokens         = 64
model.generation_config.early_stopping         = True
model.generation_config.no_repeat_ngram_size   = 0
model.generation_config.num_beams              = 4

print(f'✅ Model ready')
print(f'   Encoder params: {sum(p.numel() for p in model.encoder.parameters()):,}')
print(f'   Decoder params: {sum(p.numel() for p in model.decoder.parameters()):,}')

🖼️  Loading image processor...

preprocessor_config.json:   0%|          | 0.00/224 [00:00<?, ?B/s]

The image processor of type `ViTImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

🔤 Loading Japanese tokenizer...

tokenizer_config.json:   0%|          | 0.00/174 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

   Vocab size: 6144
   Sample: 'その手紙は届いた' → ['そ', 'の', '手', '紙', 'は', '届', 'い', 'た']
🏗️  Loading TrOCR encoder (ViT)...

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/478 [00:00<?, ?it/s]

VisionEncoderDecoderModel LOAD REPORT from: microsoft/trocr-base-printed
Key                         | Status  |
----------------------------+---------+-
encoder.pooler.dense.weight | MISSING |
encoder.pooler.dense.bias   | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

generation_config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

🏗️  Loading JP BERT decoder...

config.json:   0%|          | 0.00/516 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/366M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/204 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie bert.embeddings.word_embeddings.weight to cls.predictions.decoder.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
BertLMHeadModel LOAD REPORT from: cl-tohoku/bert-base-japanese-char-v2
Key                                                                | Status     |
-------------------------------------------------------------------+------------+-
cls.seq_relationship.weight                                        | UNEXPECTED |
bert.pooler.dense.weight                                           | UNEXPECTED |
bert.embeddings.position_ids                                       | UNEXPECTED |
cls.seq_relationship.bias                                          | UNEXPECTED |
bert.pooler.dense.bias                                             | UNEXPECTED |
bert.encoder.layer.{0...11}.crossattention.output.dense.bias       | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.query.weight       | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.value.weight       | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.key.weight         | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.value.bias         | MISSING    |
bert.encoder.layer.{0...11}.crossattention.output.dense.weight     | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.query.bias         | MISSING    |
bert.encoder.layer.{0...11}.crossattention.output.LayerNorm.weight | MISSING    |
bert.encoder.layer.{0...11}.crossattention.output.LayerNorm.bias   | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.key.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

🔗 Assembling VisionEncoderDecoderModel...
✅ Model ready
   Encoder params: 86,653,440
   Decoder params: 123,859,200

## 7. Áp dụng LoRA (ổn định hơn)

`target_modules` dùng `query/value` để khớp cả ViT encoder và BERT decoder attention.
Tăng `lora_dropout` để regularize tốt hơn, giảm nguy cơ train loss xuống nhanh nhưng val loss/CER không cải thiện.

In [ ]:
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.1,
    bias='none',
    # BERT decoder dùng query/value (không dùng q_proj/v_proj như LLaMA-style modules)
    target_modules=[
        'query', 'value',
    ],
    task_type='SEQ_2_SEQ_LM',
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
print('LoRA applied')

trainable params: 1,769,472 || all params: 212,282,112 || trainable%: 0.8335
✅ LoRA applied

## 8. Tạo dataset cho Trainer

In [ ]:
from PIL import Image

MAX_TARGET_LENGTH = 96  # tăng nhẹ để giảm cắt cụt text box dài

def preprocess(example):
    # Encode ảnh qua ViT feature extractor
    image = Image.open(example['img_path']).convert('RGB')
    pixel_values = feature_extractor(image, return_tensors='pt').pixel_values.squeeze(0)

    # Chuẩn hóa text trước khi tokenize để train/eval nhất quán
    clean_text = normalize_jp_text(example['text'])
    tokenized = jp_tokenizer(
        clean_text,
        padding='max_length',
        max_length=MAX_TARGET_LENGTH,
        truncation=True,
        return_attention_mask=False,
    )
    labels = tokenized.input_ids

    # Mask padding để không tính vào loss
    labels = [l if l != jp_tokenizer.pad_token_id else -100 for l in labels]
    return {'pixel_values': pixel_values, 'labels': labels}

train_dataset = train_dataset.shuffle(seed=42)
val_dataset   = val_dataset.shuffle(seed=42)

print('Preprocessing train set...')
train_dataset = train_dataset.map(preprocess, remove_columns=['img_path', 'text'])
print('Preprocessing val set...')
val_dataset   = val_dataset.map(preprocess,   remove_columns=['img_path', 'text'])

train_dataset.set_format(type='torch', columns=['pixel_values', 'labels'])
val_dataset.set_format(type='torch',   columns=['pixel_values', 'labels'])

print('Dataset ready')
print(f'   Train: {len(train_dataset):,} | Val: {len(val_dataset):,}')
print(f'   MAX_TARGET_LENGTH: {MAX_TARGET_LENGTH}')

Parameter 'function'=<function preprocess at 0x7fe264fdd3a0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only shown once. Subsequent hashing failures won't be shown.
WARNING:datasets.fingerprint:Parameter 'function'=<function preprocess at 0x7fe264fdd3a0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only shown once. Subsequent hashing failures won't be shown.

🔄 Preprocessing train set...

Map:   0%|          | 0/45000 [00:00<?, ? examples/s]

🔄 Preprocessing val set...

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

✅ Dataset ready
   Train: 45,000 | Val: 5,000

## 9. Training Arguments (H100 Optimized)

In [ ]:
import inspect

# Tương thích nhiều phiên bản Transformers, đồng thời đảm bảo eval/save match khi load_best_model_at_end=True
sig = inspect.signature(Seq2SeqTrainingArguments.__init__)
strategy_kwargs = {}
gc_kwargs = {}

# Trên một số bản torch/transformers + PEFT, gradient checkpointing (reentrant) gây lỗi
# "A different number of tensors was saved during forward and recomputation".
# Mặc định tắt để train ổn định hơn trên Kaggle. Nếu cần bật lại, đổi thành True.
ENABLE_GRADIENT_CHECKPOINTING = False

# Một số version dùng eval_strategy, một số dùng evaluation_strategy.
# Nếu có cả hai thì set cùng giá trị để tránh lệch.
if 'eval_strategy' in sig.parameters:
    strategy_kwargs['eval_strategy'] = 'epoch'
if 'evaluation_strategy' in sig.parameters:
    strategy_kwargs['evaluation_strategy'] = 'epoch'

if not strategy_kwargs:
    raise RuntimeError('Không tìm thấy tham số eval strategy phù hợp trong Seq2SeqTrainingArguments')

# Khi bật gradient checkpointing, ưu tiên non-reentrant để tránh mismatch tensor
if ENABLE_GRADIENT_CHECKPOINTING and 'gradient_checkpointing_kwargs' in sig.parameters:
    gc_kwargs['gradient_checkpointing_kwargs'] = {'use_reentrant': False}

training_args = Seq2SeqTrainingArguments(
    output_dir='./trocr-manga109-jpbert-lora',

    # ================== BATCH SIZE & MEMORY ==================
    per_device_train_batch_size=12,
    per_device_eval_batch_size=24,
    gradient_accumulation_steps=4,     # Effective batch size = 48
    gradient_checkpointing=ENABLE_GRADIENT_CHECKPOINTING,

    # ================== TRAINING PARAMS (STABLE) ==================
    learning_rate=3e-5,
    num_train_epochs=12,
    bf16=True,
    tf32=True,
    max_grad_norm=1.0,
    # IMPORTANT: PEFT + Seq2SeqTrainer + label smoothing có thể làm thiếu decoder_input_ids
    # và gây lỗi: "You must specify exactly one of input_ids or inputs_embeds"
    label_smoothing_factor=0.0,

    # ================== DataLoader ==================
    dataloader_num_workers=4,
    dataloader_prefetch_factor=2,
    dataloader_pin_memory=True,
    dataloader_persistent_workers=True,

    # ================== Optimizer ==================
    # LoRA params ít, không cần 8-bit optimizer để tránh nhiễu thêm
    optim='adamw_torch_fused',
    weight_decay=0.01,
    lr_scheduler_type='cosine',
    warmup_ratio=0.08,

    # ================== Logging & Eval ==================
    do_eval=True,
    logging_strategy='steps',
    logging_steps=25,
    logging_first_step=True,
    save_strategy='epoch',
    save_total_limit=3,
    load_best_model_at_end=True,

    # ================== Generation ==================
    predict_with_generate=True,
    generation_num_beams=2,
    generation_max_length=96,
    metric_for_best_model='cer',
    greater_is_better=False,

    report_to='none',
    remove_unused_columns=False,
    label_names=['labels'],
    **strategy_kwargs,
    **gc_kwargs,
 )

# Sanity check: load_best_model_at_end yêu cầu eval/save strategy phải khớp.
resolved_eval_strategy = getattr(training_args, 'eval_strategy', None)
if resolved_eval_strategy is None:
    resolved_eval_strategy = getattr(training_args, 'evaluation_strategy', None)

print('Training args ready')
print(f'   Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}')
print(f'   LR: {training_args.learning_rate} | Optim: {training_args.optim}')
print(f'   Label smoothing: {training_args.label_smoothing_factor}')
print(f'   Gradient checkpointing: {training_args.gradient_checkpointing}')
print(f'   Gradient checkpointing kwargs: {gc_kwargs}')
print(f'   Eval strategy resolved: {resolved_eval_strategy}')
print(f'   Save strategy: {training_args.save_strategy}')

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

✅ Training args ready
   Effective batch size: 128

In [ ]:
import os
import torch

os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'
torch.cuda.empty_cache()

# Không bật gradient checkpointing thủ công ở đây.
# Nếu training_args.gradient_checkpointing=True, Trainer sẽ tự xử lý enable.
model.config.use_cache = False

if training_args.gradient_checkpointing:
    print('Gradient checkpointing sẽ được bật bởi Trainer (an toàn hơn).')
else:
    print('Gradient checkpointing đang tắt để tránh lỗi checkpoint tensor mismatch.')

model = model.to('cuda')

print('✅ Memory optimization applied')
print(f'Current VRAM: {torch.cuda.memory_allocated()/1024**3:.2f} GiB')

✅ Memory optimization applied
Current VRAM: 0.79 GiB

## 10. Tạo Trainer + Compute Metrics

In [ ]:
import re
import unicodedata
import numpy as np
import evaluate
from transformers import EarlyStoppingCallback

metric_cer = evaluate.load('cer')

def normalize_for_cer(text: str) -> str:
    text = unicodedata.normalize('NFKC', text)
    text = re.sub(r'\s+', '', text)
    return text

def compute_metrics(pred):
    predictions = pred.predictions
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    # Fallback an toàn nếu predictions đang là logits
    if isinstance(predictions, np.ndarray) and predictions.ndim == 3:
        predictions = np.argmax(predictions, axis=-1)

    labels = pred.label_ids.copy()

    # Restore pad tokens để decode
    labels[labels == -100] = jp_tokenizer.pad_token_id

    pred_str  = jp_tokenizer.batch_decode(predictions, skip_special_tokens=True)
    label_str = jp_tokenizer.batch_decode(labels,      skip_special_tokens=True)

    pred_str  = [normalize_for_cer(p) for p in pred_str]
    label_str = [normalize_for_cer(l) for l in label_str]

    cer = metric_cer.compute(predictions=pred_str, references=label_str)
    return {'cer': float(cer)}

# Guard: tránh lỗi decoder_input_ids khi dùng PEFT + label smoothing trong Seq2SeqTrainer
if getattr(training_args, 'label_smoothing_factor', 0.0) and training_args.label_smoothing_factor > 0:
    print('Override label_smoothing_factor -> 0.0 để tránh lỗi decoder input với PEFT')
    training_args.label_smoothing_factor = 0.0

# ================== TRAINER ==================
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=default_data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2, early_stopping_threshold=1e-3)],
)

print('Trainer sẵn sàng (CER + early stopping)')

Downloading builder script: 0.00B [00:00, ?B/s]

✅ Trainer sẵn sàng (CER metric + predict_with_generate)

## 11. Bắt đầu Train

In [ ]:
import os
import json

train_result = trainer.train()

best_ckpt = trainer.state.best_model_checkpoint
best_metric = trainer.state.best_metric
print('Best checkpoint:', best_ckpt)
print('Best metric (CER):', best_metric)

# ==================== SAVE ARTIFACTS ====================
OUTPUT_DIR = './trocr-manga109-jpbert-lora-final'
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Với PEFT/LoRA: save adapter từ model đang được trainer giữ (đã load best model nếu bật load_best_model_at_end)
trainer.model.save_pretrained(OUTPUT_DIR)
jp_tokenizer.save_pretrained(OUTPUT_DIR)
feature_extractor.save_pretrained(OUTPUT_DIR)

# Lưu metadata để inference khôi phục đúng base model + config
save_meta = {
    'encoder_model': ENCODER_MODEL,
    'decoder_model': DECODER_MODEL,
    'max_target_length': MAX_TARGET_LENGTH,
    'best_model_checkpoint': best_ckpt,
    'best_metric_cer': best_metric,
}
with open(os.path.join(OUTPUT_DIR, 'train_meta.json'), 'w', encoding='utf-8') as f:
    json.dump(save_meta, f, ensure_ascii=False, indent=2)

# Optional: merge LoRA vào base model để inference nhanh/đơn giản hơn
MERGED_DIR = f'{OUTPUT_DIR}-merged'
try:
    merged_model = trainer.model.merge_and_unload()
    merged_model.save_pretrained(MERGED_DIR, safe_serialization=True)
    print(f'Merged model saved to: {MERGED_DIR}')
except Exception as e:
    print(f'Skip merged save (fallback adapter-only): {e}')

print(f'Training hoàn tất! Artifacts đã lưu vào: {OUTPUT_DIR}')

`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(

✅ Training hoàn tất! Model đã lưu vào: ./trocr-manga109-jpbert-lora-final

/usr/local/lib/python3.12/dist-packages/peft/utils/save_and_load.py:295: UserWarning: Could not find a config file in  - will assume that the vocabulary was not modified.
  warnings.warn(

## 12. Inference trên Val Set

In [ ]:
import os
import re
import json
import unicodedata
import torch
import evaluate
import pandas as pd
from tqdm import tqdm
from PIL import Image
from peft import PeftModel
from transformers import (
    AutoImageProcessor,
    AutoTokenizer,
    VisionEncoderDecoderModel,
    BertLMHeadModel,
)

# ==================== PATHS ====================
OUTPUT_DIR = './trocr-manga109-jpbert-lora-final'
OUTPUT_DIR_ABS = os.path.abspath(OUTPUT_DIR)
MERGED_DIR_ABS = os.path.abspath(f'{OUTPUT_DIR}-merged')

print('Loading model artifacts...')

# Load processor/tokenizer đã save từ train
feature_extractor = AutoImageProcessor.from_pretrained(OUTPUT_DIR_ABS, local_files_only=True)
jp_tokenizer = AutoTokenizer.from_pretrained(OUTPUT_DIR_ABS, local_files_only=True)

# Load metadata để đảm bảo reconstruct đúng base architecture
meta_path = os.path.join(OUTPUT_DIR_ABS, 'train_meta.json')
if os.path.exists(meta_path):
    with open(meta_path, 'r', encoding='utf-8') as f:
        save_meta = json.load(f)
    ENCODER_MODEL = save_meta.get('encoder_model', 'microsoft/trocr-base-printed')
    DECODER_MODEL = save_meta.get('decoder_model', 'cl-tohoku/bert-base-japanese-char-v2')
else:
    ENCODER_MODEL = 'microsoft/trocr-base-printed'
    DECODER_MODEL = 'cl-tohoku/bert-base-japanese-char-v2'

# ==================== LOAD MODEL ====================
if os.path.exists(MERGED_DIR_ABS):
    print(f'Found merged model: {MERGED_DIR_ABS}')
    infer_model = VisionEncoderDecoderModel.from_pretrained(MERGED_DIR_ABS, local_files_only=True)
else:
    print('Merged model not found, loading base + LoRA adapter...')

    # Build base model giống lúc train
    trocr_full = VisionEncoderDecoderModel.from_pretrained(ENCODER_MODEL)
    encoder = trocr_full.encoder
    del trocr_full

    decoder = BertLMHeadModel.from_pretrained(
        DECODER_MODEL,
        is_decoder=True,
        add_cross_attention=True,
    )
    base_model = VisionEncoderDecoderModel(encoder=encoder, decoder=decoder)

    # Load LoRA adapter theo chuẩn PEFT
    infer_model = PeftModel.from_pretrained(base_model, OUTPUT_DIR_ABS, is_trainable=False)

# ==================== GENERATION CONFIG ====================
infer_model.config.decoder_start_token_id = jp_tokenizer.cls_token_id
infer_model.config.pad_token_id = jp_tokenizer.pad_token_id
infer_model.config.eos_token_id = jp_tokenizer.sep_token_id

infer_model.generation_config.decoder_start_token_id = jp_tokenizer.cls_token_id
infer_model.generation_config.bos_token_id = jp_tokenizer.cls_token_id
infer_model.generation_config.pad_token_id = jp_tokenizer.pad_token_id
infer_model.generation_config.eos_token_id = jp_tokenizer.sep_token_id
infer_model.generation_config.max_new_tokens = 96
infer_model.generation_config.num_beams = 2
infer_model.generation_config.early_stopping = True

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
infer_model.eval()
infer_model.to(device)
print(f'Model loaded. Device: {device}')

def normalize_for_eval(text: str) -> str:
    text = unicodedata.normalize('NFKC', text)
    text = re.sub(r'\s+', '', text)
    return text

# ==================== INFERENCE FUNCTION ====================
def infer_image(image_path, max_new_tokens=96):
    image = Image.open(image_path).convert('RGB')
    pixel_values = feature_extractor(image, return_tensors='pt').pixel_values.to(device)

    with torch.no_grad():
        generated_ids = infer_model.generate(
            pixel_values=pixel_values,
            max_new_tokens=max_new_tokens,
            num_beams=2,
            early_stopping=True,
            no_repeat_ngram_size=0,
        )

    predicted_text = jp_tokenizer.decode(generated_ids[0], skip_special_tokens=True)
    return normalize_for_eval(predicted_text)

# ==================== EVAL ON VAL SUBSET ====================
VAL_IMG_DIR = '/kaggle/working/train_data/rec/val'
VAL_GT = '/kaggle/working/train_data/rec/rec_gt_val.txt'

val_samples_inf = []
with open(VAL_GT, 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        rel_path, text = line.split('\t', 1)
        img_path = os.path.join(VAL_IMG_DIR, os.path.basename(rel_path))
        if os.path.exists(img_path):
            val_samples_inf.append({
                'image_path': img_path,
                'ground_truth': normalize_for_eval(text),
            })

print(f'Val samples available: {len(val_samples_inf)}')

metric_cer = evaluate.load('cer')
results = []

for sample in tqdm(val_samples_inf[:50], desc='Inference val set'):
    pred = infer_image(sample['image_path'])
    gt = sample['ground_truth']
    results.append({
        'image': os.path.basename(sample['image_path']),
        'ground_truth': gt,
        'prediction': pred,
        'correct': gt == pred,
    })

df = pd.DataFrame(results)
print('\nInference results (first 50 val images):')
display(df)

acc = df['correct'].mean() * 100
print(f'Exact-match accuracy: {acc:.2f}%')

cer = metric_cer.compute(
    predictions=df['prediction'].tolist(),
    references=df['ground_truth'].tolist(),
)
print(f'CER on 50 samples: {cer:.4f} ({cer*100:.1f}%)')

csv_path = './trocr_inference_val_results.csv'
df.to_csv(csv_path, index=False, encoding='utf-8')
print(f'Results saved to: {csv_path}')

🔄 Đang load model LoRA + processor...

Loading weights:   0%|          | 0/478 [00:00<?, ?it/s]

VisionEncoderDecoderModel LOAD REPORT from: microsoft/trocr-base-printed
Key                         | Status  |
----------------------------+---------+-
encoder.pooler.dense.weight | MISSING |
encoder.pooler.dense.bias   | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/204 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie bert.embeddings.word_embeddings.weight to cls.predictions.decoder.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
BertLMHeadModel LOAD REPORT from: cl-tohoku/bert-base-japanese-char-v2
Key                                                                | Status     |
-------------------------------------------------------------------+------------+-
cls.seq_relationship.weight                                        | UNEXPECTED |
bert.pooler.dense.weight                                           | UNEXPECTED |
bert.embeddings.position_ids                                       | UNEXPECTED |
cls.seq_relationship.bias                                          | UNEXPECTED |
bert.pooler.dense.bias                                             | UNEXPECTED |
bert.encoder.layer.{0...11}.crossattention.output.dense.bias       | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.query.weight       | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.value.weight       | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.key.weight         | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.value.bias         | MISSING    |
bert.encoder.layer.{0...11}.crossattention.output.dense.weight     | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.query.bias         | MISSING    |
bert.encoder.layer.{0...11}.crossattention.output.LayerNorm.weight | MISSING    |
bert.encoder.layer.{0...11}.crossattention.output.LayerNorm.bias   | MISSING    |
bert.encoder.layer.{0...11}.crossattention.self.key.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

📦 Loaded from safetensors
✅ LoRA weights loaded
✅ Model LoRA đã load xong! Device: cuda
📊 Số ảnh val để test: 5000

Inference val set: 100%|██████████| 50/50 [00:32<00:00,  1.55it/s]

🎯 KẾT QUẢ INFERENCE (50 ảnh đầu tiên):

,image,ground_truth,prediction,correct
0,word_045001.png,にゃにおー,でででで・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・...,False
1,word_045002.png,しかしこれだけたくさん部品があるとは……………,のののののののののののののののののののののののの野野野野野野野野野野野野野野野野野野野野野野...,False
2,word_045003.png,塩をかけるんだっ,のののののののののののののののののにのののののののののののののののののののののののののののの...,False
3,word_045004.png,するっ,のののののののものののののののののののののののののののののののののののののののののののののの...,False
4,word_045005.png,なんだとーこっこら！待て！,ままままままままままままままのののののののののののののののののののののののののののののののの...,False
5,word_045006.png,それからおねーさんは,ののののののののもののののののののののののののののののののののののののののののののののののの...,False
6,word_045007.png,ちょっと宝,のののののののののののののものののののののののののののののののののののののののののののののの...,False
7,word_045008.png,みんなも…知ってのとおり…,のののののののののののののののものののののののののののののののののののののののののののののの...,False
8,word_045009.png,ろうかに立ってろーっ！,のののののののののののののののののののののののののののの・・・・・・・・・・・・・・・・・・...,False
9,word_045010.png,怪しい四番やな！！,でででででででで・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・...,False
10,word_045011.png,お鶴ちゃんはいつかこうなる事があるかも知れないーーそう思ってあたしに手紙をくれたんだ…...,ののののののののののののののののののののののののののの・・・・・・・・・・・・・・・・・・・...,False
11,word_045012.png,そいつは困ったなせっかく今本当の下手人が誰だかわかったのに,ああああああああああああああああああああああああああああああ・・・・・・・・・・・・・・・・...,False
12,word_045013.png,２番ホームに列車が通過します,ののののののもののののののののののののののののののののののののののののののののののののののの...,False
13,word_045014.png,今日は―何日だ？,頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂頂...,False
14,word_045015.png,ああ,ののののののののののののののののなののののののののののののののののののののののののののののの...,False
15,word_045016.png,さそうと決まればレッツゴー！,ののののののののののののののののののののののののののののののののの・・・・・・・・・・・・・...,False
16,word_045017.png,もじもじ,ののののののののもののののののののののののののののののののののののののののののののののののの...,False
17,word_045018.png,あんたまたしのぶちゃん泣かしたんだって？,あああああああああああああああああああああ............................,False
18,word_045019.png,わかってるわよ！,ののののののもののののののののののののののののののののののののののののののののののののののの...,False
19,word_045020.png,コンピュータの資料を送ったつもりだったんですがね。,のののののののののののののののののののののののののの・・・・・・・・・・・・・・・・・・・・...,False
20,word_045021.png,ねーねー支部ちょーとぷにぷににもこっち来る時なんか見れた?,ののののののののののののののののののののののののの・・・・・・・・・・・・・・・・・・・・・...,False
21,word_045022.png,マヴロス鉱山だ！！,のののののののの・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・...,False
22,word_045023.png,もうそれからはお幸ちゃんを取り戻すためになりふりかまわずサ,ああああああああああああああああああああああああああああああ・・・・・・・・・・・・・・・・...,False
23,word_045024.png,わしもう少しでヤク中毒になるとこやんか！ただじゃすまねーと思わない！？,のののののののののののののののののののの・・・・・・・・・・・・・・・・・・・・・・・・・・...,False
24,word_045025.png,いや自分が,のののののものののののののののののののののののののののののののののののののののののののののの...,False
25,word_045026.png,怒ってたと思ったら泣いたり…情緒不安定とゆーか……,のののののののののののののののののののののののののの・・・・・・・・・・・・・・・・・・・・...,False
26,word_045027.png,お女将！！,のののののののものののののののののののののののののののののののののののののののののののののの...,False
27,word_045028.png,マッチもミリタリーショップとかでしか売られてないような特殊なヤツだしちょっと意味深な感じでしょ？,ああああああああああああああ...................................,False
28,word_045029.png,なんやジャンク屋のおっさんか,そそののののののののののののののののののののののののののののののののののの・・・・・・・・・...,False
29,word_045030.png,ひっ,しののののののののののののののののののののののののののののののののののののののののののののの...,False
30,word_045031.png,またいただきだ･･････！！！,いい・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・...,False
31,word_045032.png,知らんならいばるなーっ,ののののののもののののののののののののののののののののののののののののののののののののののの...,False
32,word_045033.png,楳束の社長夫人？,そのののののののののののののののののののののののののののののののののののののののののの野野の...,False
33,word_045034.png,撃ち殺すためにね・・・,ののののののもののののののののののののののののののののののののののののののののののののののの...,False
34,word_045035.png,しかしそれでは会社の利益が,のののののののののののののののののののにのののののののののののののののののののののののののの...,False
35,word_045036.png,ハムちゃんを見たいんだって,ののののののののののののののののののののののののののののののののの・・・・・・・・・・・・・...,False
36,word_045037.png,いえいえ困ったときはお互い様ですよ,ののののののもののののののののののののののののののののののののののののののののののののののの...,False
37,word_045038.png,へえ……,ののののののののののののののののののののののののののののののののののののののののの野野野野野...,False
38,word_045039.png,うん・・・・・・,まままままままののののののののののののののののののののののののののののののののののののののの...,False
39,word_045040.png,チハルプレゼント買ったるぜ何がいい？,ああああああああああああああああ.................................,False
40,word_045041.png,ーーこの宇宙船は宇宙商人デラボ・デスさんの”イアウ・ユチウ”号,ののののののののののののののののののののののの・・・・・・・・・・・・・・・・・・・・・・・...,False
41,word_045042.png,私の方こそごめんなさい。,ののののののもののののののののののののののののののののののののののののののののののののの野野...,False
42,word_045043.png,つくりだすことができたなら治すことだって！,のののののののののののののののののののののののののののの・・・・・・・・・・・・・・・・・・...,False
43,word_045044.png,なになにープンコ王国は８日政府軍と革命軍との間で戦闘状態に入った…ウンヌンープンコ王は暗殺さ...,11・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・...,False
44,word_045045.png,あ,のののののののののののののののののののののののののののののののののののののののののののののの...,False
45,word_045046.png,300年以上続いたが決着はつかなかった,ののののののものののののののののののののののののののののののののののののののののの・のののの...,False
46,word_045047.png,何だ小松は進学じゃないのか？,ののののののののののののののののののののののののののののののののの野野野野野野野野野野野野野...,False
47,word_045048.png,がんばれば必ずできる,ののののののものののののののののののののののののののののののののののののののののののののの・...,False
48,word_045049.png,シュミ？……シュミなの…？,ままままのののののののののののののののののののののののののののののののののののののののののの...,False
49,word_045050.png,いやああー！,ののののののののののののののののののののののにののののののののののののののののののののののの...,False

✅ Exact-match accuracy: 0.00%
📊 CER thực tế trên 50 ảnh: 4.0282 (402.8%)
💾 Đã lưu kết quả vào: ./trocr_inference_val_results.csv